// Generated by CoffeeScript 2.7.0
(function() {
  let ext, i, len, patchStackTrace, ref, ref1, ref2;

  const CoffeeScript = require('./');

  const helpers = require('./helpers');

  const path = require('path');

  ({patchStackTrace} = CoffeeScript);

  // Check if Node's built-in source map stack trace transformations are enabled.
  const nodeSourceMapsSupportEnabled = (typeof process !== "undefined" && process !== null) && (process.execArgv.includes('--enable-source-maps') || ((ref = process.env.NODE_OPTIONS) != null ? ref.includes('--enable-source-maps') : void 0));

  // Node 18+ sets Error.prepareStackTrace natively as 'ErrorPrepareStackTrace'.
  // We must distinguish that from a user/library custom patch (which we must preserve).
  // Only call patchStackTrace() if no user custom function is set and
  // --enable-source-maps is not active.
  const isNodeNativePrepareStackTrace = ((ref1 = Error.prepareStackTrace) != null ? ref1.name : void 0) === 'ErrorPrepareStackTrace';

  let cacheSourceMaps = false;

  if (!((Error.prepareStackTrace && !isNodeNativePrepareStackTrace) || nodeSourceMapsSupportEnabled)) {
    cacheSourceMaps = true;
    patchStackTrace();
  }

  // Load and run a CoffeeScript file for Node, stripping any `BOM`s.
  const loadFile = function(module, filename) {
    let js, options;
    options = module.options || getRootModule(module).options || {};
    // Currently `CoffeeScript.compile` caches all source maps if present. They
    // are available in `getSourceMap` retrieved by `filename`.
    if (cacheSourceMaps || nodeSourceMapsSupportEnabled) {
      options.inlineMap = true;
    }
    js = CoffeeScript._compileFile(filename, options);
    return module._compile(js, filename);
  };

  // If the installed version of Node supports `require.extensions`, register
  // CoffeeScript as an extension.
  if (require.extensions) {
    ref2 = CoffeeScript.FILE_EXTENSIONS;
    for (i = 0, len = ref2.length; i < len; i++) {
      ext = ref2[i];
      require.extensions[ext] = loadFile;
    }
    let Module = require('module');
    const findExtension = function(filename) {
      let curExtension, extensions;
      extensions = path.basename(filename).split('.');
      if (extensions[0] === '') {
        // Remove the initial dot from dotfiles.
        extensions.shift();
      }
      // Start with the longest possible extension and work our way shortwards.
      while (extensions.shift()) {
        curExtension = '.' + extensions.join('.');
        if (Module._extensions[curExtension]) {
          return curExtension;
        }
      }
      return '.js';
    };
    Module = Object.freeze({...Module, load: function(filename) {
      let extension;
      this.filename = filename;
      this.paths = Module._nodeModulePaths(path.dirname(filename));
      extension = findExtension(filename);
      Module._extensions[extension](this, filename);
      return this.loaded = true;
    }});
  }

  (function() {    // If we're on Node, patch `child_process.fork` so that Coffee scripts are able
    // to fork both CoffeeScript files, and JavaScript files, directly.
    let binary, cpModule, fork;
    cpModule = require('child_process');
    if (!cpModule) {
      return;
    }
    ({fork} = cpModule);
    binary = require.resolve('../../bin/coffee');
    // Assign directly on the module object (not via a variable), bypassing
    // the const-mutation check while still patching the shared module reference.
    return require('child_process').fork = function(path, args, options) {
      if (helpers.isCoffee(path)) {
        if (!Array.isArray(args)) {
          options = args || {};
          args = [];
        }
        args = [path].concat(args);
        path = binary;
      }
      return fork(path, args, options);
    };
  })();

  // Utility function to find the `options` object attached to the topmost module.
  const getRootModule = function(module) {
    if (module.parent) {
      return getRootModule(module.parent);
    } else {
      return module;
    }
  };

}).call(this);
